### ISSUE TITLE
Scijava 36.0.0 breaks Mockito Wrapper tests

### ISSUE THREAD

**Issue by mdoube** [bonej-org/BoneJ2#341]
**Describe the bug**
Updating `pom.xml` to use [scijava](https://github.com/scijava/pom-scijava/) 36.0.0 leads to the Mockito wrapper tests failing when running `mvn test -P allTests`

**Expected behavior**
All the tests pass

**Additional context**
A large number of these errors are produced
```
[ERROR]   ThicknessWrapperTest.test2DImageCancelsPlugin:69 
Wanted but not invoked:
userInterface.dialogPrompt(
    <any string>,
    <any string>,
    <any>,
    <any>
);
-> at org.bonej.wrapperPlugins.CommonWrapperTests.test2DImagePlusCancelsPlugin(CommonWrapperTests.java:222)

However, there was exactly 1 interaction with this mock:
userInterface.isVisible();
-> at org.scijava.ui.DefaultUIService.getVisibleUI(DefaultUIService.java:550)
```

**Comment by mdoube** [comment]
The offending methods in this example are:
`-> at org.bonej.wrapperPlugins.CommonWrapperTests.test2DImagePlusCancelsPlugin(CommonWrapperTests.java:222)`
```
	static <C extends Command> void test2DImagePlusCancelsPlugin(
		final Gateway imageJ, final Class<C> commandClass) {
		// SETUP
		final UserInterface oldUI = imageJ.ui().getDefaultUI();
		final UserInterface mockUI = mockUIDialogPrompt(imageJ);
		final ImagePlus image = mock(ImagePlus.class);
		when(image.getNSlices()).thenReturn(1);

		try {
			// EXECUTE
			final CommandModule module = imageJ.command().run(commandClass, true,
					"inputImage", image).get();

			// VERIFY
			assertTrue("2D image should have cancelled the plugin", module
					.isCanceled());
			assertEquals("Cancel reason is incorrect", CommonMessages.NOT_3D_IMAGE,
					module.getCancelReason());
			verify(mockUI, timeout(1000)).dialogPrompt(anyString(), anyString(), any(),
					any());
		} catch (InterruptedException | ExecutionException e) {
			Assert.fail("Test timed out");
		} finally {
			imageJ.ui().setDefaultUI(oldUI);
		}
	}
```
[and](https://github.com/scijava/scijava-common/blob/9abafb2d50ec2df75edd90811ead26e47b25f0fa/src/main/java/org/scijava/ui/DefaultUIService.java#L224) (line number is weird though)
`-> at org.scijava.ui.DefaultUIService.getVisibleUI(DefaultUIService.java:550)`
```
	public List<UserInterface> getVisibleUIs() {
		final ArrayList<UserInterface> uis = new ArrayList<>();
		for (final UserInterface ui : uiList()) {
			if (ui.isVisible()) uis.add(ui);
		}
		return uis;
	}
```

**Comment by mdoube** [comment]
Looks like `getVisibleUI()` as per the error doesn't exist any more and is now `getVisibleUIs()` in the code. Digging into versions and build clashes.

**Comment by mdoube** [comment]
This bug was introduced between `35.1.1` and `36.0.0`.

**Comment by mdoube** [comment]
Maven test reports for `pom-scijava 36.0.0.`
[surefire-reports.zip](https://github.com/bonej-org/BoneJ2/files/12827478/surefire-reports.zip)

**Comment by ctrueden** [comment]
I just released pom-scijava 37.0.0 which does *not* fix this Mockito problem. But I wanted to mention that I haven't forgotten about this issue, and will try to investigate soon, and push another pom-scijava release fixing it. Thanks for the report and investigation so far, @mdoube.

**Comment by mdoube** [comment]
Thanks @ctrueden. I was thinking maybe we could try again to run these Mockito tests in the routine CI build via Github Actions. Richard pulled the slow tests out of the standard Maven build (so they have to be called specially with `mvn test -P allTests`) because they tended to cause time-outs, but that was back in the Travis or maybe Jenkins days. Would that have helped detect this breakage earlier?

**Comment by ctrueden** [comment]
> Would that have helped detect this breakage earlier?

I think so... BoneJ2 is included in the melting pot build that runs every time pom-scijava is changed, which calls `mvn clean install` with updated dependency versions and such on each component being managed. So anything that runs as part of BoneJ2's standard unit test execution should get checked during this process.

**Comment by mdoube** [comment]
I made a PR https://github.com/bonej-org/BoneJ2/pull/342 to see whether I could tweak the test configuration to make the wrapper tests run. They do, but I still get the same error even on older working versions of SciJava e.g. 34.1.0, when running as an automated build test on GitHub. Locally `mvn clean package` completes fine.

**Comment by mdoube** [comment]
Just updated pom-scijava with the latest Mockito so that wrapper tests run at all - they otherwise fail to build with an exception, on a new Eclipse installation.
https://github.com/scijava/pom-scijava/pull/264

**Comment by ctrueden** [comment]
@mdoube IIUC: with Mockito 4.11.0, the tests compile and run, but... they still fail, right? Due to the `UIService` API change to `getVisibleUI` that you describe above? To fix this, could we: A) update the code in this repository to use the newer SciJava API; or better: B) fix SciJava Common to restore the previous method signature that BoneJ2 needs here? It was not intentional to break backwards API compatibility in SJC, and I'm happy to do (B) if it's feasible. What do you think?

**Comment by mdoube** [comment]
@ctrueden there is only one offending test now, this line:

https://github.com/bonej-org/BoneJ2/blob/10a615e0532bb04895a50e5f886a92d311079c3b/Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/IntertrabecularAngleWrapperTest.java#L405-L406

Could you please advise how to make it run properly using the new API?
